name: WF-Matrix
on: workflow_dispatch
jobs:
   job1:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os:
         - ubuntu-latest
         - windows-latest
         appvr:
         - "3.10" 
         - "3.11"
         - "3.12"
         
     steps:
     - name: Print Msg 
       run: |
          echo "This is ${{ matrix.os }}-${{ matrix.appvr }}"