name: upload Artifacts
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create a file
      run: |
         echo "Hello World" > myfile.txt
         echo "Hello World123" > myfile1.txt
         pwd
         ls -l
    - name: upload Artifact
      uses: actions/upload-artifact@v7
      with:
         name: myartifact1
         path: myfile.txt         
    
    
    