name: workflow dispatch Inputs
on: 
  workflow_dispatch:
   inputs:
     env_type:
       type: environment
       required: true       
  
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - name: Print input values
      run: |
         echo "${{ vars.DB_IP }}"
         echo "${{ vars.AUTH_TYPE }}"
    