name: Testing Conditions
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Deloying Application
      if: github.ref_name== 'master'
      run: |
         echo "deployed The Application"
    - name: Build The Application
      if: github.ref_name != 'master' 
      uses: actions/checkout@v6
         
      
