name: Conditions-1 
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: This is step1
      run: |
         pwd
         sleep 10
         exit 1
    - name: This is Stage2
      run: |
         ls -lrt
         date         
    - name: This step3
      if: failure()
      run: |
          echo "Todays date is $(date)" 
               
