name: WF WORKING DIR
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: WORKING DIR
      run: |
         pwd
         ls -la
         echo "${{ github.workspace }}"
         cd app
         pwd
    - name: Build Activity
      run: |
         pwd 
             