name: WF PERMISSION
on: 
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      image_name: ghcr.io/${{ github.actor }}/image1
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: Build Image
      run: |
         ls -l
         docker build -t ${{ env.image_name }} .
         docker images
    - name: push image
      run: |
         docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
         docker push ${{ env.image_name }}
             