name: Concurency
on: 
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print msg
      run: |
         echo "Todays Date is $(date)"
         sleep 30
         echo "Todays Date is $(date) sheshi"
         echo "Todays Date is $(date) sheshivardhan kjhfasj"
  
 