name: Concurency
on: push 
concurrency:
  group: mbapp
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print msg
      run: |
         echo "Todays Date is $(date)"
         sleep 60
         echo "Todays Date is $(date) sheshi"
         echo "Todays Date is $(date) sheshivardhan kjhfasj"
  